findthemasks/findthemasks

index.html

Sorry for the extra line changes! I was messing with some of the tabbing in the code.

Addressing issue #9: Manual update based on spreadsheet entries 12-24

---

index.html

Adds more hospitals.

---

whoweare.html

Update whoweare.html #21

---

index.html
indexCatherineOriginal.html

Adds Catherine's modifications -- her original file is included in case my manual merge contains errors. Many substantial contributions. 
We've all used slightly different html formatting. Do we have a linter that can make it uniform?

Catherine's modifications

---

index-automated.html
locations-list.js
style.css

This change adds `locations-list.js` which builds out the DOM content for the locations list. The static page content within index.html has been removed. Lastly, additional styling has been added to styles.css.
**Specific notes:**
- On pageload complete, a call to the JSON endpoint gets fired off
- The result is then parsed by `toDataByLocation(data)` which organizes the raw form results into States and Cities
- This is then passed to `toHtmlSnippets(data_by_location)` which builds the html content. It's kinda gross as it's eventually just a big string, and this would likely be better as true DOM elements. But that's for later.
- Lastly, `$(".locations-list").append(html_snippets.join(" "))` is called, which adds the generated locations-list DOM content to the locations-list div.
**Some …

Dynamic locations list based upon JSON API - Separate Index for Testing

---

index-automated.html
locations-list.js
style1.css

Some styling updates and commenting out the accepts opens? filters until data is cleaned.

Updating filters and styling

---

index.html

Adds overflow-wrap for very long URLs, some styling

Styling updates to index

---

index.html

Addressing: https://github.com/r-pop/findthemasks/issues/76

Added open box guidance to "How to donate"

---

deploy.sh

Make it deploy to the real directory

---

deploy.sh
whoweare.html

Unconditional rsync on deploy. Add middle initial for Albert

---

locations-list-map.js
locations-list1.js
locations.js

This is to resolve merge issues with, and replace, https://github.com/r-pop/findthemasks/pull/61.

Expand filter descriptions for accepted items

---

index.html

Moved link for donations that can't find a site from getusppe to ppelink

---

locations-list-map.js

https://github.com/r-pop/findthemasks/issues/116

Collapse any previously opened infowindows when opening a new one.

---

.gitignore
index-map.html
locations-list-map.js

The map now zooms to the user's location and encompasses the three closest hospitals to the user. This zoom should scale in and out automatically based on the distance between hospitals and the user.
*** Note especially the addition of the geometry library in the initial API maps call on index-map.html. That library is required for the new function to work properly:
```JS
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE&libraries=geometry">
</script>
```

Added dynamic zoom to the map. 

---

.editorconfig
.gitattributes
.gitignore
README.md

Fix for README.md and adding .gitattributes and .editorconfig for consistency.

Fix for README.md and adding .gitattributes and .editorconfig

---

locations-list-map.js
public/locations-list-map.js

This works with both repeated params and comma-separated values for a single param.

Set the initial filter state for states using the URL query params.

---

public/locations-list1.js

Tested by loading /public/give.html?state=al,co&state=wv , seems to work.

Also add query-param-based state filtering to the give page.

---

public/give.html
public/index.html

Adding a bit more styling to the UI filters

Updating styling for filters section

---

public/index.html
public/locations-list-map.js

But don't autoscroll there on page load so users get to see the top of
the page first.

Scroll the list of locations into view when the filter state changes.

---

public/index.html
public/locations-list-map.js

Edge support for #66. There's some followup work to do to make the site work for older browsers. (But I'm not set up to test those right now.) Might make most sense to add a new bug for older IE versions.

Add Edge support

---

public/give.html

This was previously added to index.html but left out here.

Add an id to the locations-list div in give.html

---

functions/index.js
public/archive/index-no-map.html
public/give.html
public/index.html
public/whoweare.html

Second pass at original #135 (before The Great Reform).
----
Cleaning up "smart" quotes in meta tag attributes. And dropping in a quick shout out (I plan to do more).
**Please test** before merging; I'm pretty sure `<p">` was a mistake but shouldn't exist, but I am an alien from outer space, so I could be wrong. 👨‍🚀

Cleaning up "smart" quotes in meta tag attributes. 

---

functions/index.js

The rest is just data clutter.

Only publish approved data items.

---

public/scripts/fill-in-geocodes.js

Not sure if pulling this from findthemasks.com will work, but let's give it a shot.

Check in @susanashlock's geocoder script that was in the google sheets app.

---

functions/index.js
public/locations-list-map.js

This should free us up to rename fields in the form and localize the sucker.

Use a stable header row

---

public/give.html
public/index.html
public/locations-list-map.js
public/stats.html
public/stats.js
public/toDataByLocation.js

extracted shared function
Could someone with a little more knowledge of browser compatibility confirm that the type="module" will work here so we can share that function? I haven't written js without babel in a long time...
Once i18n.js is back in a can merge that and add in i18n strings

added basic stats page

---

public/give.html
public/index.html
public/locations-list-map.js
public/whoweare.html

Example below demonstrates if `?state=fl` and you select `DE` + `FL` states. :shipit:

Showing statistics on map on page initialization. Also rendering stats for listing when filters init/change.

---

functions/index.js

This allows us to add form entires without worrying
about breaking the geocode writeback.

Calculate the lat/lng column instead of inferring it.

---

public/give.html
public/index.html
public/toDataByLocation.js

Addresses https://github.com/r-pop/findthemasks/issues/217

Linkify the instructions field in the data shown on the map and text.

---

public/locations-list-map.js
public/stats.js
public/toDataByLocation.js

Refactoring of data_by_location to store properties at the state+city level. Improved creation of DOM elements for list view. We now create these and the map markers up front, then just swap them as the filters change.

Issue 197 : Map updates as filters change

---

functions/package-lock.json
public/give.html
public/index.html
public/request.html

References #234 to add text on index.html and give.html with the text: Your submission will be approved and updated as soon as possible.

add text to indicate delay on index and give pages

---

public/locations-list-map.js

Sort the entries within data_by_location when caching the DOM elements.

Sort city entries by name

---

public/give.html
public/index.html

Fixing bug w/ duplicate inclusion of maps API (bad merge conflict resolution). Also ensuring Places API is included.

Hotfix: Duplicate inclusion of maps API; also need places API.

---

public/locations-list-map.js

Ensuring we attempt to geocode the raw user entered text if they don't press down arrow to select an entry from Google's autosuggest. The solution is to just directly geocode the user input text, cross fingers 🤞 and go with Google's top hit.
**Here's how it looks now:**

Map search: Fix for no results on enter (without pressing down).

---

README.md
database.rules.json
deploy.sh
firebase.json
functions/.gitignore
functions/index.js
public/actions/deploy.php
public/ch/.htaccess
public/data.json

With this, the pipeline now generates a data-{country}.json
file. A symlink from data.json -> data-us.json is provided
for compatibility.
It also includes some cleanups of the data.json such that
unlabeled rows do not appear.

Clean up cloud funcs. Support fr and ch.

---

README.md

Adding doc for scripts that update Google sheet

---

public/give.html
public/i18n.js

Updates to map search ux on give.html

---

public/locations-list-map.js

Allow map focus by country

---

public/index.html
public/locations-list-map.js

Update index.html to enable map search

---

public/give.html
public/index.html
public/locations-list-map.js

Fix for the potential race condition (#287) between locations-list-map and the gmap script. The former now loads the latter on demand, if hide-map isn't set.

Load map from script

---

README.md
public/countries.js
public/i18n.js
public/index.html
public/locales.js
public/locations-list-map.js

Language + country selector for whenever we are ready to turn on France / Canada

add bottom nav for ca/fr/us

---

public/i18n.js
public/index.html

Can be made better for sure, but elevates the "Add Donation Site" CTA for now...

Updating Add Donation site CTA

---

public/locations-list-map.js

Reverts findthemasks/findthemasks#328
Was great on desktop... kinda crappy on mobile.

Revert "Update CA map center"

---

public/i18n/de-de.json
public/i18n/fr-fr.json
public/i18n/it-it.json

Smartling translations are completed for PR#338 from administrative_regions

---

public/i18n/it-it.json
public/i18n/zh-tw.json

Smartling translations are completed

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#366 from fix_masks_filter

---

public/whoweare.html

Addresses https://github.com/findthemasks/findthemasks/issues/60

Add line with github contributors

---

public/locations-list-map.js

Resolves https://github.com/findthemasks/findthemasks/issues/309

Preserve original linebreaks in the instructions strings.

---

functions/index.js
functions/package-lock.json
functions/package.json

Added an output to google cloud storage by creating a string in functions/index.js:snapshotData() and writing it out, follow the pattern for the JSON file upload.
I don't currently have a functioning test environment for this step.

Added file output to data-{country}.csv in Google storage

---

public/index.html
public/locations-list-map.js

Cities are now listed in order again, random horizontal scrollbar removed

City ordering fix, removed scrollbar, styles on give.html

---

public/locations-list-map.js

add AT, ES, IT, PT map centers

---

public/.htaccess

not sure if we want to try merging this or reverting first @nburt. It does seem unlikely to me that this `.htaccess` config change (even if done wrong the first time) would only affect the new countries and not the old ones...but I'm not really familiar with the infrastructure setup that is utilizing this config.
#425

fix filesmatch syntax (remove ~)

---

public/locations-list-map.js

Setups a google maps link in list view:
Resolves https://github.com/findthemasks/findthemasks/issues/126

Setup google maps link to each address in list view

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#442 from company_thanks

---

public/locations-list-map.js

Add google maps link to address section of marker popover

---

public/locations-list-map.js

improve map geocoder search usability by zooming to recommended viewport

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#458 from i18n_social_sharing

---

public/index.html
public/locations-list-map.js
public/style.css

Fix for French regions not having 2-char abbrevations. Prev:
Now:

Override list styles for FR

---

public/give.html

I just updated the copy below for the Give page. Not sure if I've modified the correct file but happy to make changes if not.

Updating copy below map for Canada only

---

README.md

Adding links to forms and spreadsheets, and a few words about moderation.

Adding information about data intake and storage to README.md

---

functions/index.js

While working on moving geocoding logic back into Firebase, I found some minor issues (wrong indices, wrong variables, etc.).  
Tested on -dev, Leaving annotateGeocodes commented out for now.  Next step is to pull this out into a separate function and run every ~1 minute automatically.

Fixing up some bit-rot in index.js's geocoding logic

---

README.md
public/scripts/backupSheets.js

Part of an effort with @awong-dev to make our scripts more discoverable, robust, and editable-by-all.

Backing up backup script

---

functions/index.js
functions/package-lock.json

Filter private fields

---

public/airbrake.js
public/give.html
public/index.html
public/stats.html
public/whoweare.html

Sets up airbrake so all javascript uncaught exceptions are logged and sent to the #dev channel.
Closes: https://github.com/findthemasks/findthemasks/issues/462

Setup airbrake

---

public/whoweare.html

Closes https://github.com/findthemasks/findthemasks/issues/518

Fix import issue

---

public/locations-list-map.js

change default canada center

---

public/archive/index-automated.html
public/archive/index-legacy-manual.html
public/archive/index-no-map.html
public/give.html
public/index.html
public/request.html
public/stats.html
public/whoweare.html

This will ensure IPs sent to GA are anonymized. Following directions from here:
https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization

Anonymize IPs

---

public/formEnumLookups.js

fix typo where walkie-talkie filter wasnt working

---

functions/index.js

This makes the workflow more sane if a moderator needs to
update an address.

Fill missing address and rewrite lat/lng.

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#539 from add_new_countries

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#550 from change-header

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#508 from share_links

---

public/style.css

Indent content to separate entries from each other

---

functions/index.js

Adds a log entry for every geocoded entry getting sent to google. let's monitor the logs to see if we are getting repeats or any funny behavior

Log geocoded entries

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#571 from 570_fix_form_text

---

public/countries.js

change india administrative region to state

---

package-lock.json
package.json
server.js

resolves #576
I wasn't sure what the best route to go on this was. I don't think this endpoint gets hit a lot. This turned out to be really simple from a code perspective, but it adds a dependency and may have other issues I haven't thought of. It seems to work though (and didn't break anything else).

add proxy for csv file

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#582 from i18n_meta_descriptions

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#580 from topnav

---

server.js

Fixes https://github.com/findthemasks/findthemasks/issues/577

redirect to root on 404s

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#612 from new-tab-donate

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#607 from redesign_v2

---

server.js
views/volunteer.handlebars

Sets up skeleton for volunteer page. 
Closes: https://github.com/findthemasks/findthemasks/issues/602

Setup volunteer page

---

public/getCountry.js
public/i18nUtils.js
public/locations-list-map.js
public/render-nav.js
public/sendEvent.js
public/stats.js
public/style.css
public/utils.js
views/layouts/static.handlebars
views/partials/top_nav.handlebars
views/whoweare.handlebars

Addresses https://github.com/findthemasks/findthemasks/issues/610
1. Refactored top nav rendering to its own module
2. i18n is actually not functioning on the "Who we are" page currently due to some outdated paths, fixed that up
3. Added navigation back to home page from "Who we are" by making the FTM span clickable.

Add header nav to whoweare, fixup i18n issues

---

public/locations-list-map.js

bump canada default zoom up one

---

server.js
views/layouts/give.handlebars
views/layouts/main.handlebars
views/layouts/static.handlebars
views/partials/top_nav.handlebars
views/stats.handlebars

resolves https://github.com/findthemasks/findthemasks/issues/635 (at least, first solution for it, webpack versioning will be better)

add query string versioning where possible to mitigate caching issue

---

views/whoweare.handlebars

- Add links to join us, privacy, and puts general contact info as a stopgap until we have top nav finished

Add links to other sub pages as stopgap

---

public/i18n/en.json
views/partials/top_nav.handlebars

Closes part of https://github.com/findthemasks/findthemasks/issues/666

Add link to volunteer page

---

views/donation-form-bounce.handlebars

Closes https://github.com/findthemasks/findthemasks/issues/676

Add France english donation form

---

.eslintignore
.eslintrc.json
client/locations-list-map.js
client/polyfills.js
client/render-nav.js
middleware/setBananaI18n.js
middleware/setCurrentCountry.js
package-lock.json
package.json
public/airbrake.js
utils/formatFbLocale.js
viewHelpers/getDonationFormUrl.js
viewHelpers/localizeContactInfo.js
viewHelpers/selectLargeDonationSitesPartialPath.js
viewHelpers/selectMaskMatchPartialPath.js

Tweaking some of the more annoying rules to suit my personal tastes.  Applying eslint to more scripts.

More lint, more better

---

client/locations-list-map.js

resolves https://github.com/findthemasks/findthemasks/issues/694, but investigating if I should change the data upstream instead

fix entry.orgType back to entry.org_type

---

views/partners.handlebars

Closes: https://github.com/findthemasks/findthemasks/issues/687

Fix partner links

---

functions/index.js

Just for US addresses right now. https://github.com/findthemasks/findthemasks/issues/391

add smarty streets function for us addresses

---

client/getCountry.js

https://github.com/findthemasks/findthemasks/issues/698

fix country code parsing to allow countries without trailing slash

---

server.js
views/special-projects/la-makers.handlebars

The makers in LA need a map showing vetted makers to help reduce scams
occurring locally and they need it STAT. We do maps well. Standing up
a fork of the HTML so they can get something going ASAP.

Add /special-projects/la-makers/ route

---

client/locations-list-map.js

fix openBox regression (dataset has open_box not camelcase)

---

client/locations-list-map.js
viewHelpers/getDonationFormUrl.js

@nburt I already merged your other PR so creating a new one for this additional commit

remove gb references

---

sass/style.scss
views/partials/top_nav.handlebars

resolves #749, not sure this is the best way to resolve it but it's certainly the quickest

add conditional to show different CTA button for makerspace form

---

client/locations-list-map.js

fix open box reference on left side info cards

---

client/locations-list-map.js

Updated wiki too: https://github.com/findthemasks/findthemasks/wiki/Embedding-%23findthemasks-donation-sites-page
example: https://findthemasks-filter-by--bgduqg.herokuapp.com/?accepting=homemade%20masks,gloves&orgType=hospital,Doctor%27s%20Office

Resolves #726: add the ability to filter by accepted items + org types

---

applicationRoutes.js
package-lock.json
package.json
rootRoutes.js
server.js

Also split out the routing in server.js to make it more readable.

Add in virtual host for findthemakers.com.

---

public/i18n/en.json

Clean up og:description to say maker groups.

---

sass/style.scss
views/partials/top_nav.handlebars

also including fix for https://github.com/findthemasks/findthemasks/issues/724 because it has been bugging me for a while

mobile first for partners

---

applicationRoutes.js
viewHelpers/getLocalContactEmail.js
views/faq.handlebars
views/volunteer.handlebars

add configuration of country specific contact email

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#829 from linderr-linkback-CTA

---

client/faq.js
views/faq.handlebars
views/partials/countries/ca/large_donation_sites.handlebars
views/partials/countries/ca/mask_match.handlebars
views/partials/countries/default/large_donation_sites.handlebars
views/partials/countries/us/mask_match.handlebars

- Sets up id for each FAQ question so #hyperlinks work. Sets the id on the `<dt>` but perhaps we should do it on the `<dd>`?
- Adds analytic event when a user clicks on a link to a question or expands a question

Setup FAQ for linking

---

.gitpod.yml
client/stats.js
public/i18n/en.json

Findthemasks 623

---

server.js

Hey, I just met this code and this is crazy, so test me maybe?

Add www and escape periods in vhost for makers

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#899 from surface-date-added-on-ui

---

sass/style.scss
views/partials/top_nav.handlebars

ensure logo in nav brand is clickable

---

sass/style.scss

First PR, and I'm not used to working with forks. If I'm not following protocol, please let me know the right way! Thanks.

Fixes findthemasks/findthemasks#815

---

sass/give.scss

add hover/highlighted style to give scss

---

views/blog/2020_05_14_data_update.handlebars

Fixes Saikat-noted typo, updates Lancet link, incorporates Vasu's suggestion number 5

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#915 from issue742

---

applicationRoutes.js
client/locations-list-map.js
functions/index.js
rootRoutes.js
server.js
utils/setDataset.js

Slightly hacky on the functions side, but also not sure it's worth refactoring...

Add support for getusppe regional affiliates in json.

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#941 from osms_credit

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#938 from small-fixups

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#880 from osms

---

client/locations-list-map.js
functions/airtable-connector.js
functions/airtable-shared-view.js
functions/geocode.js
functions/index.js
functions/package-lock.json
functions/package.json
public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/en.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Currently it's a csv so just parsing locally, doing the geocode
and then appending the dataset. This also adds a proper rate limit
to the geocoding API from google maps so we don't trigger the abuse
limit.

Add OSMS data into makers dataset.

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#960 from filters_v3

---

client/locations-list-map.js

Get rid of toggle for satellite / terrain views on the map, resolves #962

Remove map type toggle

---

applicationRoutes.js
client/locations-list-map.js
linkPartners.js
sass/give.scss
sass/partner-link-icons.data.svg.scss
sass/style.scss
views/layouts/give.handlebars

This is same as #957, reincarnated to get a redeploy.

(Son of) Demo third-party links with real external web site

---

client/locations-list-map.js

Row id search param is now implemented by adjusting initial map view, similar to coords.
This eliminates the repetitive calls to the bounds_changed handler, the awful logic that tried to deal with that, and the needless rebuilding of the locations list.

Streamline ?id= processing

---

apiRoutes.js
functions/api.js
functions/constants.js
functions/ftm-encrypt.js
functions/index.js
functions/package-lock.json
functions/package.json
rootRoutes.js

Support quick-click "lgtm" and "remove" buttons in mailchimp

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#1004 from feature/link-to-map-item

---

public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json

Smartling translations are completed for PR#1002 from partnerLinkInfoWin

---

package-lock.json
package.json
views/layouts/main.handlebars

In main.handlebars, I modified the title tag using {{eq}} so that the title displays #Findthemakers when we access the makers page.

Fixed findthemakers title tag

---

applicationRoutes.js
client/locations-list-map.js
linkPartners.js
public/i18n/ar-ma.json
public/i18n/de-de.json
public/i18n/en.json
public/i18n/es-es.json
public/i18n/fr-fr.json
public/i18n/hi-in.json
public/i18n/it-it.json
public/i18n/ja-jp.json
public/i18n/ko-kr.json
public/i18n/nl-nl.json
public/i18n/pl-pl.json
public/i18n/pt-pt.json
public/i18n/qqq.json
public/i18n/ru-ru.json
public/i18n/zh-tw.json
sass/partner-link-icons.data.svg.scss
views/layouts/give.handlebars

This can be tested from https://dewv.net/ftm/test.html which I temporarily updated to embed the heroku deployment.

Add partner callback links to map infowindows

---

views/give.handlebars

Reverts findthemasks/findthemasks#1048

Revert "Do not put alert in the embed"

---

apiRoutes.js
applicationRoutes.js

Print out prettier command result message.

---

.eslintrc.json
client/.eslintrc.json
client/toDataByLocation.js
client/toDataByLocation.test.js

added some unit tests for toDataByLocation. Any feedback would be appreciated!

unit tests for toDataByLocation first draft

---

client/locations-list-map.js
public/i18n/en.json

Hey @4kbt! Just finished up adding a June and later filter to the site. Did some quick testing and everything seems to work for me. Would you or @nburt care to take a look at it? Let me know if there are any questions or other things I can help with!

Added additional entry age filter for jun and later
