index-automated.html, locations-list.js
This addresses #2 by adding a filter for the following items:
* State
* Materials accepted
* "Accepts open boxes/bags"
The following is a preview of the implemented functionality:
=> Add dynamic filter to `index-automated.html`

index.html
This is to prevent the page from jumping when styling is loaded from Twitter. This attempts to address https://github.com/r-pop/findthemasks/issues/64.
=> Add fixed height to twitter row

public/index.html
This should prevent a race condition where initMap (via
DOMContentLoaded) can sometimes be called before the map script has been
downloaded.
=> Load the google maps script with 'defer' only, not 'async'.

functions/index.js
Mostly fixes #144 .
Currently it only fills 5 lat/longs at a time. There needs to be rate limiting code to stay under the 50qps of the Geolocation API, otherwise the geolocation server starts rejecting requests.
=> Backfill geolocation into spreadsheet

public/locations-list-map.js
This adds a polyfill for Edge to fix bug when filtering by state; due to lack of support for HTMLCollection.prototype.forEach. See below.
=> Fix bug when filtering by state in Edge.

public/index.html, public/locations-list-map.js
Now that the filters update both the map and the list, I'm re-ordering the Donations section to be:
- filters
- map
- list
We then display only one list count, and a single "Donation sites (num)" header.
This works with ?hide-map and ?hide-filters.
However, this breaks the "?hide-list" option, but that's not a big issue on index.
=> Updates to section ordering on index.html

public/give.html, public/index.html, public/locations-list-map.js, public/toDataByLocation.js
Fix for the list view being generated via createElement / createTextNode. Links in the instructions paragraph need to be linkified after the element exists, or the HTML gets treated as plain text.
A little unfortunate the same instructions in the map marker infowindow gets processed as HTML string, but at least both instances work now.
=> Linkify instructions at usage point

public/toDataByLocation.js
Raw data doesn't have consistent case in the Cities field, so we can wind up with duplicate entries in the rendered list.
=> Dedup cities in parsed data

public/locations-list-map.js
The geocoder takes time. Entries can be approved, but not yet located. In that case, don't show them on the map because they end up in the ocean off the coast of Ghana.
=> Do not map entries that have no geocodes

getting_started.md
Addressing #210 
A few users were tripped up by the way the instructions were formatted, so I split them out into the backend and the frontend.  Most people just want to run the frontend anyway.
=> Split out install instructions for backend/frontend

public/locations-list-map.js
Default value is 2, so if any duplicate entries are present in the data, they will never split out to individual pins. Biggest group of dups we can find contains 4, so 5 is the magic number here!
=> Set minimum cluster size

public/locations-list-map.js
@awong-dev - slight tweak to your country table. fractional zooms look okay initially, but as soon as you touch the map, it zooms out to the next whole zoom level unexpectedly.
=> Adjust centers; round down zooms

public/index.html, public/locations-list-map.js
Revamp of how the active filters are tracked, for both map and list. There's now a data object that tracks the available filters and their current states. The UX elements are created based on this object (or not, if hide-list and/or hide-filters are set). State is synced between the UX elements and any ?state= params on page load.
Fixes some jank in onFilterChanged, especially WRT calling it directly at startup to handle ?state= settings.
Also simplifies the "Reset map" behavior, since it can just revert to what the filters object holds, instead of tracking the initial filters separately.
Fixes #304
=> Add filters state object

public/i18n.js, public/locations-list-map.js
Now that we are loading the strings with XHR, there is occasionally a race condition where data.json is loaded before the translations. This only shows up for countries with a small amount of data. This PR should fix it to wait until strings are loaded to render any content that depends on them.
=> Do not render the list of sites until i18n is loaded

public/index.html
I pasted this in slack for coworkers, and it used french for the website description preview. Slack might just be dumb and use the first `<meta property="og:description">` it finds. Swapping language preferences in Slack did not seem to matter. In this case, you might want to put english first.
Tested out the meta tag ordering on a toy site:
=> Slack's website preview always uses french

public/locations-list-map.js
Adds tracking for the equipment and state map filters.
Everytime a map filter is created created an analytics event with these properies:
**Category**: `map`
**Action**: `filter-getItems` or `filter-states`
**Label**: key of the filter clicked (i.e. `WA` or `mask`)
=> Add GA tracking for clicking map filters

public/locations-list-map.js
Creates a GA event when:
- user resets map
- user centers map to their location
- user sets locale
- user sets language
- user does an autocomplete map search
- user does an autocomplete map search and the location is missing
- user does a map search
- user does a map search and we are unable to geocode
Also renames the category of events on the state & equipment filters from `map` to `filters`
Part of https://github.com/findthemasks/findthemasks/issues/317
=> Create analytic events for map controls and i18n

public/locations-list-map.js
Noticed an unhandled exception using the search controls after filtering the map. If you pick a state with fewer than three pins (thanks, North Dakota!), the hard-coded loop bounds tries to access markers that don't exist. Updated to account for this.
=> Center sparse map

public/index.html, public/locations-list-map.js
This should improve pageload times a great deal, and fix Android map performance issues. Implements both parts 1 and 2 of #378.
Page should look and work the same. Here are the before and after from the profiler:
=> Render the list 40 entries at a time with infinite scroll.

public/locations-list-map.js
We've gone back and forth on whether changing a filter should scroll to the list, to the map, or not at all. How about a solution where we scroll to the map if it's available, or to the list if the page was created with ?hide-map=true? I'm probably biased since I want to show off the show-others feature, so I'm open to feedback on this behavior...
=> Scroll to map on filter change

public/locations-list-map.js
Quick fix for #264, simply clears the text field when resetting the map. Basically the idea is that when you click reset map, it only resets the map itself and the positioning and has nothing to do with filters per se.
=> Fixes #264: Clear search field when resetting map.

public/style.css
Quick CSS cleanup - sorted properties, merged/eliminated redundant properties, etc.
Added a min-width to the filter labels so the state abbreviations all appear the same size. That's been bugging me for a few days now. :-)
=> Clean up CSS

public/locations-list-map.js
Remove the show-others opt-in. Show other countries' markers for all.
=> Turn on show-others behavior by default

public/locations-list-map.js
Move call to loadOtherCountries to after map script loads and map is initialized with the primary markers. Fixes a script exception if the other country data loads before map script loads, or if the map isn't showing at all.
=> Unhandled script exception

functions/index.js
The address.replace() below explodes if the address column is undefined.
=> Handle empty addresses.

public/locations-list-map.js
Minor perf improvement to list rendering. jquery.append is a little expensive for what's basically a convenience method around Node.appendChild. Our ce() method already had logic to append a list of children, so extract this to a separate method.
=> Eliminate jquery.append

public/airbrake.js
We were creating airbrake alerts when people were testing on their local machines, this code change removes automatic alerts if the environment isn't production
=> Change automatic airbrake alerting to only happen in production'

functions/index.js
This function will allow us to do geocoding on Firebase and use our Maps API quota instead of our limited freebie quota that we're currently using.  Intended to be called from Apps Script using a time-based trigger.
=> New geocode firebase function

views/index.handlebars
I would like to bring up the map higher into the page to test if this improves conversion rates so I have cut out some content. Here are the changes: 
- removes the imagery of PPE (I'd like to put this on another page eventually)
- remove the tag line and makes the CTA a direct explanation of what our site does.
- remove line to share with industry friends since we will have share links
- removes the facebook share line since we have a PR to handle share links
The net effect is this brings our two main interactions i) adding a donations site ii) browsing the map, much further up in the page. On desktop you can reac the map in about 2 pages of scrolling now. I'd like to test out if this change will result in a net increase in the % of people who view a donation site on our page. If doesn't …
=> Test if cutting out content will improve conversion %

client/internationalizeLinks.js, views/partials/top_nav.handlebars
The new top nav wasn't setting events to google analytics - this fixes that.
=> Add back analytics to top nav social sharing

public/i18n/ar-ma.json, public/i18n/de-de.json, public/i18n/en.json, public/i18n/es-es.json, public/i18n/fr-fr.json, public/i18n/hi-in.json, public/i18n/it-it.json, public/i18n/ja-jp.json, public/i18n/ko-kr.json, public/i18n/nl-nl.json, public/i18n/pl-pl.json, public/i18n/pt-pt.json, public/i18n/ru-ru.json, public/i18n/zh-tw.json, sass/give.scss
* Add consistent 1rem bottom margin under all map embeds.
* Remove inline margin on add/edit donation form buttons for all languages.
* Style .add-donation-form in CSS instead using line height, that way it only creates margin between the button and the text when the design breaks with multiline text above it for small screens.
=> Add Margin Under Map Embed

README.md
We have embed instructions in 2 different places which doubles the amount of work for documentation. Let's just have the readme link to the wiki page
=> Removed embed instructions

applicationRoutes.js, client/locations-list-map.js
Previously, when a user set `hide-list=true` this would also enable `hide-filters=true` because the filters only worked on the list view in v1.
In the v2 world, filters work in either view (map or list), so it doesn't make sense for one feature to toggle another.
=> Change so hide-list has no effect on hide-filters

sass/give.scss
Now that the list view is shown side by side with the map, the map embed isn't really taking up the full height available in an iframe embed on desktop. 
Bumping up the embed body height to 70vh to fill up more of the height on large screens. This translates to a min iframe height of ~650px before scroll bars are shown on the embed. Takes up most of the iframe height now at more usable large iframe heights.
Note that pushing the iframe height past 750px starts making the white space gap noticeable again, but achieving true responsiveness is gonna more a more in depth change.
=> Make embed take up more of iframe height

rootRoutes.js
All data is in the makers-us.json datafile so serving that file
for all country-specific URLs.
=> HACK: Always use the makers-us datafile contents

client/locations-list-map.js, public/images/icons/growMap.svg, public/images/icons/shrinkMap.svg, views/index.handlebars, views/partials/contact_form.handlebars
When Google Maps fullscreen mode is activated, it interferes with Bootstrap modals, popovers, the CAPTCHA challenge window, etc. Any content that is not displayed through the Maps API is invisible, hidden "under" the map.
This disables Maps fullscreen mode and implements custom fullscreen logic that displays only the nav bar and the map. Since the map element is not in fullscreen mode, there is no interference with other content.
=> Add custom fullscreen logic to avoid GMap, Bstrap conflict

public/i18n/ar-ma.json, public/i18n/de-de.json, public/i18n/en.json, public/i18n/es-es.json, public/i18n/fr-fr.json, public/i18n/hi-in.json, public/i18n/it-it.json, public/i18n/ja-jp.json, public/i18n/ko-kr.json, public/i18n/nl-nl.json, public/i18n/pl-pl.json, public/i18n/pt-pt.json, public/i18n/ru-ru.json, public/i18n/zh-tw.json, sass/style.scss, views/give.handlebars, views/index.handlebars, views/special-projects/la-makers.handlebars
Address some small UI fixups:
#873, #913, #937 
To handle the layout on larger tablets or smaller desktop screens, shrink the font size and spacing a bit like so:
=> Small fixups

client/locations-list-map.js, sass/style.scss, views/give.handlebars
I noticed that `getFlatFilteredEntries` was being called twice on page load, which seemed kind of expensive. Both calls were coming from `refreshList`, which was called once explicitly, and once because map bounds were "changing" to their initial values.
I thought it might be pretty simple to avoid that redundancy. Much later, I have this, which eliminates all of these unneeded(?) steps:
- the redundancy already mentioned
- building the location list when `?hide-list=true`
- building the map markers when `?hide-map=true`
It also displays stats when `?hide-map=true`, which does not now happen in production. I think because of a bad/outdated jQuery selector that I modified.
=> Refresh list once

functions/airtable-connector.js
Was causing cascading failures.
=> Disallow exceptions from one maker dataset to stop another from loading

views/volunteer.handlebars
The Translations team blurb on the Join Us page is no longer invisible.
=> Made translations team blurb visible on Join Us page

client/locations-list-map.js
Changing the way we are filtering by entry_age to use the timestamp instead of the entry_age value. I also changed the filter ranges so that the most recent entries that are updated 0 days ago are included for the filter updated 1-7 days ago.
=> Use timestamp for entry_age filter

client/locations-list-map.js
To address the issue raised by @tobiasdeml, I just added some code to showMarkers() in location-list to check for additional datasets like makers. This should work for any additional datasets we want to potentially add in the future too!
=> Update filter now also changes secondary datasets
